# Generated by Django 5.1.6 on 2025-03-13 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_appUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nombre_usuario',
            field=models.CharField(max_length=50),
        ),
    ]
