# Generated by Django 5.1.6 on 2025-03-18 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_appUser', '0003_usuario_is_active_usuario_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nombre_usuario',
            field=models.CharField(max_length=50),
        ),
    ]
