# Generated by Django 5.1.6 on 2025-02-21 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('_appUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opcion_Votacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateField()),
                ('cedula_creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_appUser.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Participante_Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_union', models.DateField()),
                ('es_admin', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_appUser.usuario')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_appTrip.viaje')),
            ],
        ),
        migrations.CreateModel(
            name='Nota_Importante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=25)),
                ('contenido', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_appUser.usuario')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_appTrip.viaje')),
            ],
        ),
        migrations.CreateModel(
            name='Votacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=150)),
                ('fecha_creacion', models.DateField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_appUser.usuario')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_appTrip.viaje')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta_Votacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_respuesta', models.DateField()),
                ('opcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_appTrip.opcion_votacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_appUser.usuario')),
                ('votacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_appTrip.votacion')),
            ],
        ),
        migrations.AddField(
            model_name='opcion_votacion',
            name='votacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_appTrip.votacion'),
        ),
    ]
