# Generated by Django 5.1.6 on 2025-03-14 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_appTrip', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='destino',
        ),
    ]
