# Generated by Django 5.1.6 on 2025-02-21 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_appTrip', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='nota_importante',
            table='Nota_Importante',
        ),
        migrations.AlterModelTable(
            name='opcion_votacion',
            table='Opcion_Votacion',
        ),
        migrations.AlterModelTable(
            name='participante_viaje',
            table='Participante_Viaje',
        ),
        migrations.AlterModelTable(
            name='respuesta_votacion',
            table='Respuesta_Votacion',
        ),
        migrations.AlterModelTable(
            name='viaje',
            table='Viaje',
        ),
        migrations.AlterModelTable(
            name='votacion',
            table='Votacion',
        ),
    ]
