# Generated by Django 5.1.6 on 2025-03-14 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_appTrip', '0002_remove_viaje_destino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
